language: node_js
node_js:
  - "10.16"
  - "8.16"
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: "$access_key_id"
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"
  app: "mychess"
  env: "Mychess-env"
  bucket_name: "lv428chess"
after_deploy:
  - npm start
  - npm run client
